export const initialEvents = [
  {
    id: 1,
    title: "Marathon",
    image: "/image/evento1.jpg",
    description: "Annual marathon race in A Coruña",
    location: "A Coruña",
  },
  {
    id: 2,
    title: "Football Match",
    image: "/image/evento2.jpg",
    description: "Friendly football match between local teams",
    location: "Santiago de Compostela",
  },
  {
    id: 3,
    title: "Basketball Tournament",
    image: "/image/evento3.jpg",
    description: "Regional basketball tournament",
    location: "A Coruña",
  },
  {
    id: 4,
    title: "Swimming Competition",
    image: "/image/evento4.jpg",
    description: "Open water swimming competition",
    location: "Ferrol",
  },
  {
    id: 5,
    title: "Cycling Race",
    image: "/image/evento5.jpg",
    description: "Professional cycling race through the city",
    location: "Oleiros",
  },
  {
    id: 6,
    title: "Tennis Tournament",
    image: "/image/evento6.jpg",
    description: "International tennis tournament",
    location: "Ribeira",
  },
  {
    id: 7,
    title: "Volleyball Match",
    image: "/image/evento7.jpg",
    description: "Local volleyball match",
    location: "Cariño",
  },
  {
    id: 8,
    title: "Golf Championship",
    image: "/image/evento8.jpg",
    description: "National golf championship",
    location: "A Coruña",
  },
  {
    id: 9,
    title: "Horse Racing",
    image: "/image/evento9.jpg",
    description: "Annual horse racing event",
    location: "Bergondo",
  },
  {
    id: 10,
    title: "Sailing Regatta",
    image: "/image/evento10.jpg",
    description: "International sailing regatta",
    location: "Ares",
  },
];
